package deployment

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/privat655/VPSmith/internal/executionbundle"
)

const coreGeneratedInventoryTarget = "/var/lib/vpsmith/core/generated/inventory.json"

func generateCoreArtifacts(req CoreRequest, definition coreDefinition, images []executionbundle.ImageIdentity, platform corePlatform) ([]GeneratedArtifact, error) {
	desired, err := generateCoreDesired(req, definition, images)
	if err != nil {
		return nil, err
	}
	imageByName := make(map[string]executionbundle.ImageIdentity, len(images))
	for _, image := range images {
		imageByName[image.Name] = image
	}
	caddy, ok := imageByName["caddy"]
	if !ok {
		return nil, fmt.Errorf("resolved Core image caddy is missing")
	}
	authelia, ok := imageByName["authelia"]
	if !ok {
		return nil, fmt.Errorf("resolved Core image authelia is missing")
	}
	quadletRoot := filepath.Join("/home", req.AdminUser, ".config/containers/systemd")
	artifacts := []GeneratedArtifact{
		desired,
		textArtifact("generated/journald.conf", "/etc/systemd/journald.conf.d/90-vpsmith-core.conf", 0o644, `[Journal]
Storage=persistent
SystemMaxUse=200M
RuntimeMaxUse=50M
`),
		textArtifact("generated/coredump.conf", "/etc/systemd/coredump.conf.d/90-vpsmith-core.conf", 0o644, `[Coredump]
Storage=none
ProcessSizeMax=0
`),
		textArtifact("generated/tmp.mount", "/etc/systemd/system/tmp.mount", 0o644, `[Unit]
Description=VPSmith hardened temporary directory
Before=local-fs.target

[Mount]
What=tmpfs
Where=/tmp
Type=tmpfs
Options=mode=1777,strictatime,nosuid,nodev,noexec,size=25%

[Install]
WantedBy=local-fs.target
`),
		textArtifact("generated/modprobe-blocklist.conf", "/etc/modprobe.d/90-vpsmith-core-blocklist.conf", 0o644, coreModuleBlocklist()),
		textArtifact("generated/sysctl.conf", "/etc/sysctl.d/90-vpsmith-core.conf", 0o644, coreSysctl()),
		textArtifact("generated/audit.rules", "/etc/audit/rules.d/90-vpsmith-core.rules", 0o640, coreAuditRules()),
		textArtifact("generated/rootless-network.conf", "/etc/containers/containers.conf.d/90-vpsmith-rootless.conf", 0o644, `[network]
default_rootless_network_cmd="pasta"
`),
		textArtifact("generated/caddy-edge-http.socket", "/etc/systemd/system/caddy-edge-http.socket", 0o644, edgeSocket("HTTP", 80)),
		textArtifact("generated/caddy-edge-http.service", "/etc/systemd/system/caddy-edge-http.service", 0o644, edgeService("HTTP", "caddy-edge-http.socket", 8080)),
		textArtifact("generated/caddy-edge-https.socket", "/etc/systemd/system/caddy-edge-https.socket", 0o644, edgeSocket("HTTPS", 443)),
		textArtifact("generated/caddy-edge-https.service", "/etc/systemd/system/caddy-edge-https.service", 0o644, edgeService("HTTPS", "caddy-edge-https.socket", 8443)),
		textArtifact("generated/Caddyfile", "/var/lib/vpsmith/core/caddy/Caddyfile", 0o644, coreCaddyfile(req, platform)),
		textArtifact("generated/authelia-configuration.yml", "/var/lib/vpsmith/core/authelia/configuration.yml", 0o644, coreAutheliaConfiguration(req, platform)),
		textArtifact("generated/vpsmith-core.network", filepath.Join(quadletRoot, "vpsmith-core.network"), 0o640, `[Network]
NetworkName=vpsmith_core
Driver=bridge
Internal=true

[Install]
WantedBy=default.target
`),
		textArtifact("generated/vpsmith-egress.network", filepath.Join(quadletRoot, "vpsmith-egress.network"), 0o640, `[Network]
NetworkName=vpsmith_egress
Driver=bridge

[Install]
WantedBy=default.target
`),
		textArtifact("generated/authelia.container", filepath.Join(quadletRoot, "authelia.container"), 0o640, autheliaQuadlet(req, authelia)),
		textArtifact("generated/caddy.container", filepath.Join(quadletRoot, "caddy.container"), 0o640, caddyQuadlet(req, caddy, platform)),
	}
	inventory, err := coreInventoryArtifact(req, artifacts, platform)
	if err != nil {
		return nil, err
	}
	artifacts = append(artifacts, inventory)
	return artifacts, nil
}

func textArtifact(path, target string, mode int64, value string) GeneratedArtifact {
	return artifact(path, target, mode, []byte(value))
}

func coreModuleBlocklist() string {
	modules := []string{"cramfs", "freevxfs", "jffs2", "hfs", "hfsplus", "udf", "dccp", "sctp", "rds", "tipc"}
	var b strings.Builder
	b.WriteString("# Generated by VPSmith Core.\n")
	for _, module := range modules {
		fmt.Fprintf(&b, "install %s /bin/false\nblacklist %s\n", module, module)
	}
	return b.String()
}

func coreSysctl() string {
	return `# Generated by VPSmith Core.
net.ipv4.ip_unprivileged_port_start = 1024
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.log_martians = 1
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.randomize_va_space = 2
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
`
}

func coreAuditRules() string {
	return `# Generated by VPSmith Core.
-w /etc/ssh/sshd_config -p wa -k vpsmith-ssh
-w /etc/ssh/sshd_config.d/ -p wa -k vpsmith-ssh
-w /etc/sudoers -p wa -k vpsmith-sudo
-w /etc/sudoers.d/ -p wa -k vpsmith-sudo
-w /etc/passwd -p wa -k vpsmith-identity
-w /etc/group -p wa -k vpsmith-identity
-w /etc/fail2ban/ -p wa -k vpsmith-fail2ban
-w /etc/ufw/ -p wa -k vpsmith-ufw
-w /etc/sysctl.conf -p wa -k vpsmith-sysctl
-w /etc/sysctl.d/ -p wa -k vpsmith-sysctl
-w /etc/audit/ -p wa -k vpsmith-audit
`
}

func edgeSocket(label string, port int) string {
	return fmt.Sprintf(`[Unit]
Description=VPSmith public %s socket for rootless Caddy

[Socket]
ListenStream=0.0.0.0:%d
NoDelay=true

[Install]
WantedBy=sockets.target
`, label, port)
}

func edgeService(label, socket string, targetPort int) string {
	return fmt.Sprintf(`[Unit]
Description=VPSmith %s socket proxy to rootless Caddy
Requires=%s
After=%s

[Service]
Type=notify
ExecStart=/usr/lib/systemd/systemd-socket-proxyd --connections-max=4096 127.0.0.1:%d
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
DynamicUser=yes
RestrictAddressFamilies=AF_INET AF_UNIX
`, label, socket, socket, targetPort)
}

func coreCaddyfile(req CoreRequest, platform corePlatform) string {
	authDomain := "auth." + req.Domain
	return fmt.Sprintf(`{
	email %s
	admin off
	servers {
		protocols h1 h2
	}
}

(access_log) {
	log {
		format json
	}
}

(security_headers) {
	header {
		-Server
		Strict-Transport-Security "max-age=31536000"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "same-origin"
		Permissions-Policy "geolocation=(), microphone=(), camera=()"
	}
}

(strip_identity) {
	request_header -Remote-User
	request_header -Remote-Groups
	request_header -Remote-Email
	request_header -Remote-Name
	request_header -X-Forwarded-User
	request_header -X-Forwarded-Groups
	request_header -X-Forwarded-Email
	request_header -X-Forwarded-Name
}

(authelia) {
	route {
		import strip_identity
		forward_auth authelia:9091 {
			uri /api/authz/forward-auth
			copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
		}
	}
}

http://%s {
	redir https://%s{uri} permanent
}

%s {
	import access_log
	import security_headers
	import strip_identity
	encode zstd gzip
	reverse_proxy authelia:9091
}

%s
:80, :443 {
	import access_log
	import security_headers
	respond "not found" 404
}
`, req.ACMEEmail, authDomain, authDomain, authDomain, renderCoreModuleSites(platform))
}

func coreAutheliaConfiguration(req CoreRequest, platform corePlatform) string {
	return fmt.Sprintf(`theme: auto
default_2fa_method: totp

server:
  address: tcp://:9091/
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth

log:
  level: info

totp:
  issuer: auth.%s

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: auth.%s
      policy: bypass
%s
session:
  name: authelia_session
  same_site: lax
  inactivity: 15m
  expiration: 8h
  remember_me: 1M
  cookies:
    - domain: %s
      authelia_url: https://auth.%s

regulation:
  modes:
    - user
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notification.txt
`, req.Domain, req.Domain, renderCoreAutheliaRules(platform), req.Domain, req.Domain)
}

func imageWithDigest(image executionbundle.ImageIdentity) string {
	return image.Ref + "@" + image.Digest
}

func autheliaQuadlet(req CoreRequest, image executionbundle.ImageIdentity) string {
	secretRoot := "/var/lib/vpsmith/secrets/core"
	return fmt.Sprintf(`[Unit]
Description=VPSmith Authelia
After=vpsmith-core-network.service
Wants=vpsmith-core-network.service

[Container]
ContainerName=authelia
Image=%s
Network=vpsmith-core.network
NetworkAlias=authelia
User=1000:1000
UserNS=nomap
Volume=/var/lib/vpsmith/core/authelia/configuration.yml:/config/configuration.yml:ro
Volume=/var/lib/vpsmith/core/authelia/data:/data
Volume=%s/%s:/config/users_database.yml:ro
Volume=%s/%s:/run/secrets/session:ro
Volume=%s/%s:/run/secrets/storage:ro
Volume=%s/%s:/run/secrets/reset-password:ro
Environment=AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
Environment=AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/storage
Environment=AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/reset-password
Exec=--config /config/configuration.yml
ReadOnly=true
Tmpfs=/tmp:rw,noexec,nosuid,nodev,size=64m
NoNewPrivileges=true
DropCapability=all
PidsLimit=1024

[Service]
Restart=always
TimeoutStartSec=900

[Install]
WantedBy=default.target
`, imageWithDigest(image), secretRoot, req.Secrets.AutheliaUsersDatabase, secretRoot, req.Secrets.AutheliaSession, secretRoot, req.Secrets.AutheliaStorage, secretRoot, req.Secrets.AutheliaResetPassword)
}

func caddyQuadlet(req CoreRequest, image executionbundle.ImageIdentity, platform corePlatform) string {
	var extraNetworks strings.Builder
	for _, network := range platform.Networks {
		fmt.Fprintf(&extraNetworks, "Network=%s\n", network)
	}
	return fmt.Sprintf(`[Unit]
Description=VPSmith Caddy public edge
After=vpsmith-core-network.service vpsmith-egress-network.service authelia.service
Wants=vpsmith-core-network.service vpsmith-egress-network.service authelia.service

[Container]
ContainerName=caddy
Image=%s
Network=vpsmith-egress.network
Network=vpsmith-core.network
%sNetworkAlias=caddy
User=1000:1000
UserNS=nomap
PublishPort=127.0.0.1:8080:80/tcp
PublishPort=127.0.0.1:8443:443/tcp
Volume=/var/lib/vpsmith/core/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
Volume=/var/lib/vpsmith/core/caddy/data:/data
Volume=/var/lib/vpsmith/core/caddy/config:/config
ReadOnly=true
NoNewPrivileges=true
DropCapability=all
AddCapability=NET_BIND_SERVICE
PidsLimit=2048

[Service]
Restart=always
TimeoutStartSec=900

[Install]
WantedBy=default.target
`, imageWithDigest(image), extraNetworks.String())
}

type generatedCoreInventory struct {
	SourceID         string               `json:"source_id"`
	Version          string               `json:"version"`
	PackageSHA256    string               `json:"package_sha256"`
	AuthDomain       string               `json:"auth_domain"`
	PublicRoutes     []CorePublicRoute    `json:"public_routes,omitempty"`
	Units            []generatedCoreUnit  `json:"units"`
	Containers       []string             `json:"containers"`
	Networks         []string             `json:"networks"`
	Caddy            generatedCoreCaddy   `json:"caddy"`
	Authelia         generatedCoreService `json:"authelia"`
	ManagedArtifacts []string             `json:"managed_artifacts"`
}
type generatedCoreUnit struct {
	Name  string `json:"name"`
	Scope string `json:"scope"`
}
type generatedCoreCaddy struct {
	Unit       generatedCoreUnit `json:"unit"`
	Container  string            `json:"container"`
	ConfigPath string            `json:"config_path"`
}
type generatedCoreService struct {
	Unit      generatedCoreUnit `json:"unit"`
	Container string            `json:"container"`
}

func coreInventoryArtifact(req CoreRequest, artifacts []GeneratedArtifact, platform corePlatform) (GeneratedArtifact, error) {
	managed := make([]string, 0, len(artifacts))
	for _, item := range artifacts {
		managed = append(managed, item.TargetPath)
	}
	managed = append(managed, coreGeneratedInventoryTarget)
	sort.Strings(managed)
	inventory := generatedCoreInventory{
		SourceID: req.Source.SourceID, Version: req.Source.Version, PackageSHA256: req.Source.PackageSHA256,
		AuthDomain:   "auth." + req.Domain,
		PublicRoutes: publicRouteExpectations(platform),
		Units:        []generatedCoreUnit{{Name: "caddy-edge-http.socket", Scope: "system"}, {Name: "caddy-edge-https.socket", Scope: "system"}, {Name: "authelia.service", Scope: "user"}, {Name: "caddy.service", Scope: "user"}},
		Containers:   []string{"authelia", "caddy"}, Networks: []string{"vpsmith_core", "vpsmith_egress"},
		Caddy:            generatedCoreCaddy{Unit: generatedCoreUnit{Name: "caddy.service", Scope: "user"}, Container: "caddy", ConfigPath: "/etc/caddy/Caddyfile"},
		Authelia:         generatedCoreService{Unit: generatedCoreUnit{Name: "authelia.service", Scope: "user"}, Container: "authelia"},
		ManagedArtifacts: managed,
	}
	data, err := json.MarshalIndent(inventory, "", "  ")
	if err != nil {
		return GeneratedArtifact{}, err
	}
	data = append(data, '\n')
	return artifact("generated/core-inventory.json", coreGeneratedInventoryTarget, 0o400, data), nil
}
